subtle tweaks and refactoring

diff --git a/conan-dl b/conan-dl
--- a/conan-dl
+++ b/conan-dl
@@ -15,6 +15,8 @@
 # default variable assignments
 startingdir="$PWD"
 tmpdir="${TMPDIR:-/tmp}"
+refresh="0.5" # Refresh time for the tui download meter, in seconds
+watch="no"
 menu="fzf" # Also see config file, it re-defines this if the value is set.
 # Source the config file
 . "${XDG_CONFIG_HOME:-$HOME/.config}/conan-dl/conan-dl.conf" # in `dash`, the source command does not exist, but . does the same thing
@@ -29,6 +31,7 @@ depcheck() {
     done
 }
 
+# Read command-line options
 while getopts ":s:a:f:l:r:o:m:hwd" opt; # Long options would be nice, but limit portability.
 do
     case $opt in
@@ -53,14 +56,28 @@ Conan-dl. Use at thy peril.
 EOF
             exit 0
             ;;
-        w)    watch=yes ;; # not implemented. Maybe in the future when this is merged into ani-cli?
+        w)    watch="yes" ;; # not implemented. Maybe in the future when this is merged into ani-cli?
         d)    depcheck; exit ;;
         *)    echo "Invalid option. Go home."; exit ;;
     esac
 done
 
-# Clean up values
-resolution=$(echo $resolution | sed 's/p$//;s/P$//')
+# Integer check. Necessary for lastep resolution.
+is_integer(){
+    case "${1#[+-]}" in
+        (*[!0123456789]*) return 1 ;;
+        ('')              return 1 ;;
+        (*)               return 0 ;;
+    esac
+}
+
+# Clean up resolution
+get_resolution(){
+    # Remove trailing P from end of resolution
+    echo $resolution |
+        sed 's/p$//;s/P$//'
+}
+resolution=$(get_resolution)
 
 # Get a feel for the terminal
 LINES=$(tput lines)
@@ -68,21 +85,9 @@ COLUMNS=$(tput cols)
 # _=$((totaleps=(lastep-firstep+1) ))
 # _=$((termstart=(LINES-totaleps-1) ))
 
-search_eps () {
-    # get final episode number of $animiegg
-    animegg=$1
-    curl -s "https://$streamsite/category/$animegg" |
-    sed -n -E '
-        /^[[:space:]]*<a href="#" class="active" ep_start/{
-        s/.* '\''([0-9]*)'\'' ep_end = '\''([0-9]*)'\''.*/\2/p
-        q
-        }
-        '
-}
-
 # Display human-readable info. Sanity check.
-echo "Anime: $anime"
-echo "Episodes: $firstep to $lastep"
+echo "Approximate anime: $anime"
+echo "Trying episodes: $firstep to $lastep"
 echo "Resolution: $resolution"
 
 search_anime () {
@@ -97,17 +102,19 @@ search_anime () {
 }
 
 get_animegg() {
-search_anime "$anime" |
-    $menu
+    anime="$*"
+    search_anime "$anime" |
+        $menu
 }
-
-animegg=$(get_animegg)
-
-[ $lastep = 'END' ] &&
-    lastep=$(search_eps $animegg)
+animegg=$(get_animegg "$anime")
 
 # BROKEN
-#[ $watch == "yes" ] >/dev/null && echo "Go use ani-cli, you lazy scum" || echo "Downloading"
+# [ "$watch" = "yes" ] >/dev/null && echo "Go use ani-cli, you lazy scum" || echo "Downloading"
+case $watch in
+    yes)        echo "Go use ani-cli, you lazy scum" && exit ;;
+    no)         echo "Downloading" ;;
+esac
+
 echo "Actual anime: $animegg"
 
 get_embedurl() {
@@ -128,8 +135,9 @@ get_streamurl() {
         s/.*(https[^'\'']*).*/\1/p
         q
         }
-        ')
-    printf '%s' "$streamurl" | sed -n -E "s/(.*)\.m3u8/\1.$resolution.m3u8/p"
+        '
+    )
+    echo "$streamurl" | sed -n -E "s/(.*)\.m3u8/\1.$resolution.m3u8/p"
 }
 get_episode() {
     epnum=$1
@@ -146,7 +154,35 @@ get_episode() {
         #"--output ep.$epnum.%(ext)s" \
 }
 
-eps=$(seq "$firstep" "$lastep" 2>/dev/null || cat "${XDG_CONFIG_HOME:-$HOME/.config}/conan-dl/eplist.list")
+get_lastep () {
+    # get final episode number of $animegg
+    animegg=$1
+    curl -s "https://$streamsite/category/$animegg" |
+    sed -n -E '
+        /^[[:space:]]*<a href="#" class="active" ep_start/{
+        s/.* '\''([0-9]*)'\'' ep_end = '\''([0-9]*)'\''.*/\2/p
+        q
+        }
+        '
+}
+
+get_eps(){
+    [ -f "$outputdir/eplist.list" ] &&
+        eps=$("cat $outputdir/eplist.list")
+    firstep=$1
+    lastep=$2
+# [ $lastep = 'END' ] &&
+#     lastep=$(get_lastep $animegg)
+# Below does the same thing better
+    # is_integer $firstep &&
+    is_integer $lastep ||
+        lastep=$(get_lastep "$animegg")
+
+    # is_integer $firstep &&
+    is_integer $lastep &&
+        eps=$(seq "$firstep" "$lastep")
+}
+eps=$(get_eps $firstep $lastep)
 
 mkdir -p "$outputdir" && cd "$outputdir"
 mkdir -p "$tmpdir/cdl/$animegg"
@@ -162,17 +198,17 @@ do
 done
 
 tput sc
-while true
+while pgrep yt >/dev/null 2>/dev/null
 do
     tput rc
     >"$tmpdir/cdl/$animegg/statusall.tmp"
-    for epnum in $eps
+    for epnum in "$eps"
     do
-        tail -n 1 "$tmpdir/cdl/$animegg/$epnum.status" >> "$tmpdir/cdl/$animegg/statusall.tmp"
+        tail -n 1 "$tmpdir/cdl/$animegg/$epnum.status" >> "$tmpdir/cdl/$animegg/statusall.tmp" &
         # rm $tmpdir/cdl/$epnum.status
     done
     cat "$tmpdir/cdl/$animegg/statusall.tmp"
-    sleep 0.5
+    sleep $refresh
 done
 exit
 
